[package]
name = "supersid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = "0.8.1"
complot = "0.3.4"
libc = "0.2.149"
num-traits = "0.2.17"
welch-sde = "0.1.0"
